;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "clojars-integration")
(def path ".")
(def version "0.1.1")
(def tag "0.1.1")
(def generated-at "2020-12-07T22:41:45Z")
