;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "clojars-integration")
(def path ".")
(def version "0.1.3")
(def tag "0.1.3")
(def generated-at "2020-12-07T23:10:22Z")
