;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "clojars-integration")
(def path ".")
(def version "0.1.5")
(def tag "0.1.5")
(def generated-at "2021-01-15T04:59:12Z")
